### ISSUE TITLE
Downloaded Windows zip gets detected as "Trojan:Win32/Wacatac.H!ml"

### ISSUE THREAD

**Issue by T4bletopG4mes** [Windows200000/TwitchDropsMiner-updated#145]
### Description

As the title describes, win zip gets detected as trojan by windows security.

### To Reproduce

Download the Twitch.Drops.Miner.Windows.zip file on a (64-bit) windows machine

### Expected behavior

Shouldnt be detected as virus.

### Observed behavior

File gets deleted by windows defender/security.

### Screenshots

![image](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/174814735/dfe3be80-88f5-4963-b1c7-e3b740dfacc7)

### OS

Windows 10 (64-bit)

### Build

Twitch.Drops.Miner.Windows.zip

### Version/Commit

v15.7.1

**Comment by Windows200000** [comment]
Always been this way. There's not much that can be done as long as pyinstaller is used to make the exe.

**Comment by T4bletopG4mes** [comment]
Not for me, its the first time this happens.

**Comment by Windows200000** [comment]
What I noticed, is that Windows got used to it, but I started having the issue again when I downloaded it multiple times, thus giving the zip a different name. Maybe it happened the first time that you don't remember and now something changed. Either way, this is not a new thing and is not easily fixable. You can search through issues in DevilXD's upstream to find mroe details.

**Comment by T4bletopG4mes** [comment]
Even though I allowed the zip and unzipped it, now (after a restart) windows defender deleted the .exe...there has to be a way to make it not show up as a trojan.. I 100% didnt have this problem before, otherwise I would have posted about it before.

**Comment by T4bletopG4mes** [comment]
The other problem is that it gets detected as a virus by brave and as suspicious by chrome so its not a windows defender problem..

**Comment by T4bletopG4mes** [comment]
Is there too much code to move away from pyhton? I know it will be very annoying but since you said pyinstaller is the the thing causing the problem, it makes sense moving away from it.

**Comment by Totesfleisch** [comment]
Good fucking Lord how many more Times does this have to be discussed? I have this Project subbed with email notifs to keep updated on Issues and it starts to be annoying enough to call it out. 

The whole fucking Project is right here on Github, you can look at all the Files yourself and see that theres nothing wrong with it.

If you want it to not get deleted, add a Folder to the Windows Defender / AV Exception and be done with it, if youre that scared of a AV calling out random Shit which has been an Issue since the Dawn of Time, then stop using it. If you want it to move away from pyinstaller so bad, feel free to do it yourself. It's LITERALLY a non-relevant Issue.

**Comment by Windows200000** [comment]
@Totesfleisch No need to be rude.

@T4bletopG4mes If you have the time, feel free to rewrite it in Rust or however you want. I do not consider it worth it to spend weeks of time to eliminate a warning, if I could spend that time fixing bugs and improving the program instead.

If you are concerned about security, you should inspect and download the source code, then build it yourself anyway, as GitHub allows the repo owner to upload any file they want to releases.
