### ISSUE TITLE
Twitch is down, retrying

### ISSUE THREAD

**Issue by Windows200000** [Windows200000/TwitchDropsMiner-updated#172]
# Are you experiencing this error? Please tell me!
I have it working for myself, where it tries more URLs and if it fails, doesn't get stuck in a retry loop.
If other people have it, I will prioritize cleaning it up and make a commit.

---

### Description

After a while, TDM gets stuck with the message `Twitch is down, retrying in x seconds...`

### To Reproduce

1. Start TDM

### Expected behavior

it mines

### Observed behavior

It retries, only very rarely actually mining

### OS

Windows 11

### Build

.exe

### Version/Commit

v15.8.2

### Additional context

Might be correlated with `Summer Vibes Token Store: Drop 6` from `World of Tanks`.

**Comment by Windows200000** [comment]
I have gotten to this being the issue, why exactly it repeatedly tried to connect to an invalid url? idk...

2024-08-17 23:50:16: Twitch is down, retrying in 118 seconds...
Response: <ClientResponse(https://video-weaver.fra05.hls.ttvnw.net/v1/playlist/CvgEBj5v92UmilGcMzOfowkkBT1k9noaOcIXhhNj1MY_i1Po5veCSlX4o0Cxv_WitGB0MTtjvv1KlxDsLIY3sTnPwQsEa2zLttwaJT3A3MQs1um4gbV06AkU5bkF8MQgoxMQxwYlXy_dDmp6uaMkW1kd7vl1S7ZbYJ2IyGQSNJE7lDVfhwThK3pIv91Iit8uZqPg8R24xGN5I0uxfboPwCunNkQ6HqUs02Hxvzgs76IYiKazZd7xCK1kCLh4OBSkrijmgM7W4FYGCwJHHZ2eWQJDs-5qsx5LoEvmq8WhyE4ZK-F0V3DUjzL2j2FtVVAanaccI-SasuPqnthqEtfINHp1s2ba5FL2uhCvCoWBJ2sOphBXYV_U7iVMV3tkFuWKpg4VRvlhWPoCDe89sP9U-tl-V9XTD0_IA1IXeYewtpwJ_kLbOlmeFJXL3-Hj_fzktenDZ7hvq1Bo30S1MiMZALkXIO4zLuIQapkJA3uWUxMrYidatysOs19RSmOMAjAKthA7uqtLfqOAJ8AWYwpenqCHCYX3cjOrrBkKk2ZeXQbF1ive3amSbGhJrxE40kA1wmgsIb81LQLGZUN9YpAa1bpdxlsJXbpoaMS0EVzuOCaE2PG-gIMOhS9IjM0KJd1VwTYILS3ynilsw1hw9XTz6sI_xpXbp0C2aWn138QswMko80ffrMzr2fd58sSOjz6l2WJ4u8w4TWzQvRCjQ-WXCHGKrJZVAeGjLwiRHCYwRlxa39RPGh0FR6W_DZlWHnG4dSZZfLMgFtxJuulJkqNtasDCkdh4Nh830IEBq89ytV099wptpAUwYhpME3JUUpiMCnTJ5AxolWFUwAsaDAHLRu3TyL490LHLNyABKglldS13ZXN0LTIwlQo.m3u8) [500 Internal Server Error]>
<CIMultiDictProxy('Content-Type': 'text/plain; charset=utf-8', 'Vary': 'Accept-Encoding', 'x-content-type-options': 'nosniff', 'x-error-message': 'CLUSTERDOWN Hash slot not served', 'Date': 'Sat, 17 Aug 2024 21:50:14 GMT', 'Content-Length': '22', 'Access-Control-Allow-Origin': '*')>

**Comment by Windows200000** [comment]
![image](https://github.com/user-attachments/assets/eb1dcfef-ec68-4c12-825c-240303f33c3f)
So the Twitch site gets a list of links to m3u8 playlists that work, while TDM gets one where instead of the playlists a `500 Internal Server Error` gets returned.

**Comment by Windows200000** [comment]
I finishes mining `Summer Vibes Token Store: Drop 6` from `World of Tanks` and the issue persists. It also looks like not all links have to be broken in the response TDM gets.

**Comment by Windows200000** [comment]
The issue seems to be it gets one bad url and then just retries that one again and again instead of trying to get another one. I'll look deeper tmrw.

**Comment by Windows200000** [comment]
Of 60 requests, 57 went through and 3 failed with all 4 different broadcast qualities. Maybe I made a mistake yesterday when I thought I figured out that it's not always all broken or all working.

**Comment by Windows200000** [comment]
So immediately retrying the send_watch function makes it work. This means we can probably just do that after the first fail.

A pretty serious issue is that TDM doesn't stop counting down once it fails. This is a really difficult issue to solve, because a lot of the code still relies on minute intervals. I hacked the new 20s on top by just not advancing a minute if there is still seconds remaining. That means nothing checks if 2/3 of the requests even succeeded, and it's just assumed they did.

**Comment by Windows200000** [comment]
here you can check what I currently have: https://github.com/Windows200000/TwitchDropsMiner-updated/compare/in-dev...Windows200000:TwitchDropsMiner-updated:issue-172-ttv-down-retrying

**Comment by Skay100** [comment]
For me it completely freezes, one it unfreezes I do get the error but any action on the program freezes it again, before the error everything was completely fine.

**Comment by Windows200000** [comment]
Compile from the fork in my above comment. This seems to be pretty rare. Or take this exe:
[Twitch Drops Miner (by DevilXD).json](https://github.com/user-attachments/files/16681983/Twitch.Drops.Miner.by.DevilXD.json)

**Comment by notNSANE** [comment]
yes, im having this issue and progress is being reset too, very annoying

**Comment by Skay100** [comment]
Sadly your exe doesn't work for me too. 3/50 Websockets connected, at first it gets channel list, ends up breaking on rewards that might be a subscription reward, goes back to "gathering channels" and can't connect to Twitch again. (which freezes the app constantly)

**Comment by Windows200000** [comment]
@Skay100 @notNSANE
> Sadly your exe doesn't work for me too. 3/50 Websockets connected, at first it gets channel list, ends up breaking on rewards that might be a subscription reward, goes back to "gathering channels" and can't connect to Twitch again. (which freezes the app constantly)

The subscription reward is ignored. You have to rename the [Json I sent 3 messages above](https://github.com/Windows200000/TwitchDropsMiner-updated/issues/172#issuecomment-2299782005) to an exe. GitHub doesn't allow executables in comments. Try clearing your cookies file and logging in again too.

**Comment by Sparh4wk** [comment]
> @Skay100 @notNSANE
> 
> > Sadly your exe doesn't work for me too. 3/50 Websockets connected, at first it gets channel list, ends up breaking on rewards that might be a subscription reward, goes back to "gathering channels" and can't connect to Twitch again. (which freezes the app constantly)
> 
> The subscription reward is ignored. You have to rename the [Json I sent 3 messages above](https://github.com/Windows200000/TwitchDropsMiner-updated/issues/172#issuecomment-2299782005) to an exe. GitHub doesn't allow executables in comments. Try clearing your cookies file and logging in again too.

sadly its the same...
![Snímek obrazovky 2024-08-22 171808](https://github.com/user-attachments/assets/2a38a729-1341-49fd-8215-efb062b1e007)



![image](https://github.com/user-attachments/assets/a016cbd5-58d2-46ad-97b5-d86a88797800)

**Comment by JourneyOver** [comment]
> Compile from the fork in my above comment. This seems to be pretty rare. Or take this exe: [Twitch Drops Miner (by DevilXD).json](https://github.com/user-attachments/files/16681983/Twitch.Drops.Miner.by.DevilXD.json)

This seems to be working for me, it did freeze like others mentioned for a minute at most while it was gathering channels but then it eventually unfroze, threw a connection error for a slight bit and then it started working just fine.

I do get random:
```
13:04:06: ERROR:  NOT ERROR: Successfully watched after 0 retries.
13:04:27: ERROR:  NOT ERROR: Successfully watched after 0 retries.
13:04:48: ERROR:  NOT ERROR: Successfully watched after 0 retries.
```

things coming up in the output section a ton but it at least seems to be progressing on twitch drops as well.

![Screenshot 2024-08-22 130814](https://github.com/user-attachments/assets/8cfc0909-eeee-4634-9ae8-1e820ff30580)

**Comment by Windows200000** [comment]
yup, the error not error is what I used to try and figure out what;s going on, you can ignore that. The freeze doesn't affect me, I guess it's a separate issue?

**Comment by JourneyOver** [comment]
> the error not error is what I used to try and figure out what;s going on, you can ignore that

Yea I kind of figured that it could be ignored for the most part.

> The freeze doesn't affect me, I guess it's a separate issue?

Possibly, I only had it freeze the one time during the gathering channels bit and it was a very short amount of time that the window was frozen, other than that everything seems to be running fine for me though so far for the past 3 hours that I've been running the version posted above.

**Comment by JourneyOver** [comment]
Ooop I ran into it now just throwing twitch is down forever after I had a intermitten downtime of my internet, I ended up shutting down TDM for the time being that my internet was down and once my internet was back up I re-opened TDM again and it has just been stuck on `cannot connect to twitch, retrying in X seconds` ever since.

**Comment by luisf371** [comment]
Using the update .exe provided above, im still receiving the error.
Let me know if there's any logging i can provide to assist.
![image](https://github.com/user-attachments/assets/4ade581e-df86-48d5-abbf-0b6c9f7cb99a)

**Comment by zelda0079** [comment]
Delete the cookies.jar.

**Comment by JourneyOver** [comment]
> Delete the cookies.jar.

That doesn't really make any difference on my end.

**Comment by zelda0079** [comment]
> > Delete the cookies.jar.
> 
> That doesn't really make any difference on my end.

This is temporary fix when it is happening.

**Comment by Windows200000** [comment]
I put it into in-dev because I'm still really busy unfortunately. I will be running it on my end as well and if it owrks I'll make a release

**Comment by JourneyOver** [comment]
So far everything has been running perfectly on my end \^^

**Comment by JourneyOver** [comment]
Have no issue with TDM freezing still, but did run into the `Twitch is down, retrying in x seconds...` loop again. Only solution was to delete the `cookies.jar` file and relog in again to create a new `cookies.jar` file.

**Comment by zelda0079** [comment]
> Have no issue with TDM freezing still, but did run into the `Twitch is down, retrying in x seconds...` loop again today. Only solution was to delete the `cookies.jar` file and relog in again to create a new `cookies.jar` file after doing that everything started working again.

You can copy cookies.jar(4kb) as a backup, you don't need to log in again.

**Comment by Windows200000** [comment]
Weird, that it still happens, because it's been working for me over a couple of days with at least a dozen of mined hours.

I guess I'll keep this open for now, but if it happens, please use [v15.9.0](https://github.com/Windows200000/TwitchDropsMiner-updated/releases/tag/v15.9.0), and upload the full log, ran with `-vvv --debug-gql --debug-ws --log`.

(You have to run it via CMD, a shortcut, Win + R or similar to be able to add the arguments)

**Comment by Skay100** [comment]
It started working today for me (I was clearing cookies every day), I was experiencing every single issue known to mankind including miner slowing down my PC to absurd degree, today after cookies/cache clear it works flawlessly again (from your exe provided in earlier comments). It's more responsive than ever.

**Comment by JourneyOver** [comment]
> Weird, that it still happens, because it's been working for me over a couple of days with at least a dozen of mined hours.

It had been working fine for me as well for the past couple of days since switching over the in-dev code, so far this has been the second time only that it has happened, but the thing that was weird about this one was that it was still mining (albiet it kept returning the same progress on an item drop but it was still actually progressing on other items when I viewed my twitch inventory) while throwing the connection error like how it shows in the following snippet from my logs:

 ```
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
CALL: Successfully watched after 0 retries.
CALL: returned watch, succeeded: True, repeat_new: False
CALL: No drop update from the websocket received
Progress: 120/120 - Campaign(Call of Duty: Black Ops 6, COD Beta 2024, 1/4)
CALL: Drop progress from active search: Calling Card  (Call of Duty: Black Ops 6, 120/120)
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
Cannot connect to Twitch, retrying in 180 seconds...
```

Was stuck doing something along those lines even though it was still actually progressing on other items in the same campaign until I did the whole shutdown, deleted the cookies file and restarted everything and then everything started working fine again and been since.

**Comment by JourneyOver** [comment]
So I had it happen again, with it getting stuck on the whole `cannot connect to twitch` bit and the whole it being stuck on a single drop, this time around though once I shut down the container (I am running this all through docker btw) to try and run it with the whole `-vvv --debug-gql --debug-ws --log` bit, it started working again without me having to do the deletion/replacing of the `cookies.jar` file or anything.

one thing I do notice in my logs though that I downloaded from my container before I restarted to run it with the debug stuff was that I was running into the following error being spammed every so often as well when it seems to start up the connection issue/being stuck on a single drop.
```
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.12/http/cookies.py:295: ResourceWarning: unclosed <socket.socket fd=35, family=2, type=1, proto=6, laddr=('172.18.0.25', 46066), raddr=('151.101.194.214', 443)>
```
(The raddr is different for each one that comes up)
any other time before I hit that problem I never see the resource warning stuff (I actually cought it doing it this time unlike previously but I'm sure it was probably happening previously as well.

anyways I'm running with the debug info running for now so if I catch it again, I'll throw up the log from my container. if it does happen is there any important stuff I should remove from the log beforehand @Windows200000 ?


also is it these two lines [here](https://github.com/Windows200000/TwitchDropsMiner-updated/blob/master/twitch.py#L1522-1523) that control the `Cannot connect to Twitch, retrying in X seconds` thing or is it somewhere else? as looking up connection stuff it seems the only thing I can find is translation stuff and then the few lines there..

**Comment by Windows200000** [comment]
> @Windows200000, if it does happen, is there any sensitive information I should remove from the log beforehand?

I didn't add any, but DevilXD might have. I know none of these are sensitive:
`{'operationName': 'DropCampaignDetails', 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e7acdecb05429a62f5984bdcb27ee938ae20543579bf73c3ae44e7c822bc4f54'}}, 'variables': {'channelLogin': '209080157', 'dropID': '969c83d3-6374-11ef-ac41-0a58a9feac02'}}`

I just asked him and will reply again once I get an answer.

**Comment by This-Person** [comment]
I never had this issue previously but I downloaded 15.9.0 because I like to make sure I'm up to date. After that I constantly got the retrying error. I downloaded 15.8.2 again but the error persisted with that version too even though it didn't happen with that version before. Both versions of the app felt very sluggish and froze a lot when trying to access inventory/settings.

I downloaded DevilXD's latest version and dropped it into the same folder and that is working fine. Very strange issue.

I've made a log I can send over if you need 👍

**Comment by JourneyOver** [comment]
It is strange thing though, as even when I run the application side of things instead of going and running through docker, I haven't experienced the sluggish/freeze issue that others have mentioned any other than the very first time I ran the in-dev version that was mentioned way above before 15.9.0 was released, any other time I've ran the application I've not experienced it since, even though I have still experienced the connection error several times now.

Still waiting for the error to happen again on my end but so far haven't seen it again since I started back up with the debug flags 6 hours ago >.<

**Comment by This-Person** [comment]
> @This-Person can you try running the `-vvv --debug-gql --debug-ws --log` flags as mentioned in [#172 (comment)](https://github.com/Windows200000/TwitchDropsMiner-updated/issues/172#issuecomment-2322318548) and see if it produces anything while it's throwing to the cannot connect to twitch error? That's the type of log he is trying to get right now is with those flags.

I won't lie I have no idea what I'm looking at but I can't see any obvious errors. Lots of messages like this in a row for different channel names:

2024-08-31 09:38:02.887:	  DEBUG:	GQL Request: {'operationName': 'VideoPlayerStreamInfoOverlayChannel', 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'HASH'}}, 'variables': {'channel': 'zigueira'}}

Then after those messages stop a lot of messages like this in a row for different channel names:

2024-08-31 09:38:31.382:	  DEBUG:	GQL Response: {'data': {'user': {'id': '172985691', 'profileURL': 'https://www.twitch.tv/legionlooterana', 'displayName': 'LegionLooterana', 'login': 'legionlooterana', 'profileImageURL': 'https://static-cdn.jtvnw.net/jtv_user_pictures/07da15c9-084f-4eea-a8d6-e3f96f405d1d-profile_image-150x150.png', 'broadcastSettings': {'id': '172985691', 'title': 'Jugamos y opinamos sobre Call of duty Black Ops 6 #Playstation5 #Directo #MasterChef', 'game': {'id': '1672324422', 'displayName': 'Call of Duty: Black Ops 6', 'name': 'Call of Duty: Black Ops 6', '__typename': 'Game'}, '__typename': 'BroadcastSettings'}, 'stream': None, '__typename': 'User'}}, 'extensions': {'durationMilliseconds': 57, 'operationName': 'VideoPlayerStreamInfoOverlayChannel', 'requestID': 'REQUESTID'}}

I've removed the requestID and sha256Hash just in case they're identifiable.

As I say without changing anything at all, deleting the 15.9.0 exe and dropping DevilXD's latest exe into the same folder instead makes everything work again. No idea what's causing it.

**Comment by Windows200000** [comment]
>  requestID and sha256Hash

The hash is hard-coded for the persistent query, and the requestID is likely invalid after a very short time.

However, DevilXD said, that at some point the authorization token might get logged, which would be a pretty huge issue, that's pretty much the same thing as malicious extensions, that steal your cookies and can gain access to your sessions (logins).

**Comment by Windows200000** [comment]
Actually, yeah, there's the auth_token in there, which isn't great.

Try using only `-vvv`, that won't allow me to see exactly what's going on, but it should ensure there is no "raw" requests and responses, that contain most of the stuff your PC and Twitch needs to communicate.

**Comment by Sparh4wk** [comment]
adding my logfile if someone is interested
[log.txt](https://github.com/user-attachments/files/16824716/log.txt)

**Comment by Windows200000** [comment]
@Sparh4wk remove it, it contains your auth token. Sorry for not clarifying that, I wasn't aware myself. I'll add you to a GH support ticket I have about this.

**Comment by Windows200000** [comment]
@Sparh4wk

They're all deleted now by GitHub support, including yours.

**Comment by Sparh4wk** [comment]
> @Sparh4wk
> 
> They're all deleted now by GitHub support, including yours.

Thanks. I was afk till now

**Comment by This-Person** [comment]
I can confirm that after 4 or 5 minutes the CPU usage goes down, the 'cannot connect to Twitch, retrying' error disappears, the app stops freezing/being sluggish and the app starts mining normally. I've let it run for 10 mins to get a wee -vvv log which I'll attach here, hopefully it helps! If you need a more in depth log let me know and I can e-mail it over or something 👍

[log.txt](https://github.com/user-attachments/files/16826106/log.txt)


Edit: At 22:28 I pushed reload in the Settings to enable autostart and the CPU usage spiked again and the error returned for another few minutes if something looks weird in the log.

**Comment by This-Person** [comment]
Apologies for the double post but wanted to give a small update. I switched my laptop on this morning and the 15.9.0 app just auto launched normally. No high CPU usage or error messages, it just checked the inventory then got straight into mining. Very strange!

**Comment by JourneyOver** [comment]
Unsure of why this was closed fully as it is still an on-going issue here and there. I do seem to notice a huge spike in CPU/Ram while it's running into the twitch is down retrying error, upon reloading the program (or container) the usage does go back to normal until it hits the retrying error again.

I did switch back over to the `-vvv` as suggested so there isn't really a whole lot that can be pulled from the log from the looks of it sadly but I'll push it up regardless..

[twitchdropsminer-2024-09-02T23-50-19.log](https://github.com/user-attachments/files/16841909/twitchdropsminer-2024-09-02T23-50-19.log)

**Comment by Windows200000** [comment]
> Unsure of why this was closed fully as it is still an on-going issue.

I closed it, because I thought it was a separate issue, since it has been completely resolved for me

> I do seem to notice a huge spike in CPU/Ram that others are talking about while it's running into the twitch is down retrying error, upon reloading the program (or in my case the container) the usage does go back to normal until it goes and hits the problem again.

Thanks a ton for the log! It seems like it is now retrying every 2 seconds, which is not good. But it is quite likely caused by the container. Python is really not the right programming language for this, so the exe is janky solution that generates the .py fiels in a temp directory before running them. If you look ath the forks of the upstream, there should be another one, that is meant to be run in docker. I strongly suggest you use that.

From README.md:

>TDM is not intended for/as:
>
>- Mining channel points - again, it's about the drops: only. The current points you're getting are a byproduct of getting the drops, not the main goal of it.
>- Mining anything else besides Twitch drops - no, I won't be adding support for a random 3rd party site that also happens to rely on watching Twitch streams.
>- Unattended operation: worst case scenario, it'll stop working and you'll hopefully notice that at some point. Hopefully.
>- 100% uptime application, due to the underlying nature of it, expect fatal errors to happen every so often.
>- Being hosted on a remote server as a 24/7 miner.
>- Being used with more than one managed account.
>- Mining campaigns the managed account isn't linked to.

**Comment by Valentin-Metz** [comment]
@Windows200000 do you plan on merging your fork with devils upstream?
Is there any reason this has not been done already (@DevilXD seems to be active again)?
I'm also experiencing the issues @JourneyOver mentioned, so I wonder whether I should put in the effort to port back to the original upstream.

**Comment by Windows200000** [comment]
> @Windows200000 do you plan on merging your fork with devils upstream?
> Is there any reason this has not been done already (as @DevilXD seems to be active again)?
> I'm also experiencing the issues @JourneyOver mentioned, so I wonder whether I should put in the effort to port back to the original upstream.

I am looking to merge it. The issue is that FevilXD doesn't like some parts, like the prioritize by ending soonest whcih I didn't arite and thw dark mpde, whichbhe would rather be implemented more cleanly, even if you then can't switch while the app ia open.

I'll work on that once I have some time, hopwfully relatively soon.

**Comment by DevilXD** [comment]
Since I've been mentioned here, and read that y'all have an issue with the "Gathering channels..." phase of the reload process, I figured I'd shed some light on this.

The reason it freezes and gets into the "Can't connect to Twitch" loop, is because this fork still tries to set all ACL channels online at once on reload:

https://github.com/Windows200000/TwitchDropsMiner-updated/blob/42fe40423fcf77930efb962792f45d12fc195882/twitch.py#L913-L917

..., while I disabled that almost a month ago: https://github.com/DevilXD/TwitchDropsMiner/commit/f705cc1527e806bb979df9e0dbd077d93728160c

The cause of this is Twitch implementing a rate-limit on GQL requests, that'll return "Unauthorized" if there's lots of GQL requests being sent at once, which is exactly what happens when the channel status is loaded in the code above, and there's a lot of channels to load. Ref issue on my repo: https://github.com/DevilXD/TwitchDropsMiner/issues/526

Disabling this piece of code means that the miner may throw the "No available channels to watch. Waiting for an ONLINE channel..." message into the output window once the reload finishes, but it can be safely ignored. The channels are still gathered, the websocket still subscribes to channel status updates, and Twitch will still send channel status updates to the miner, including the "viewcount" event, that is sent repeatedly every so often (every like 30s), which main purpose is to update the viewer count for a stream - btw that's how you can see the viewer count updated in real time under a stream on the website.

Once the event arrives, the miner processes it into updating the channel's entry on the Channels list. But if the channel's status happens to be OFFLINE, the miner realizes it has an outdated channel state, and sets it online: https://github.com/Windows200000/TwitchDropsMiner-updated/blob/42fe40423fcf77930efb962792f45d12fc195882/twitch.py#L1233-L1245

Setting a channel online has a 2 minutes of a delay added to it, because the usual way a channel is set ONLINE, is by receiving the "stream-up" event. and these events are usually sent way before the stream actually starts. These 2 minutes are really generous, as the actual delay roughly matches the usual delay you get from watching a stream, if you've ever watched someone stream and respond to chat messages, it's more like 30 seconds max instead of the 2 minutes, but I've never really bothered min-max optimizing this - some delay was needed, 2 minutes worked, I just left it at that.

So shortly after a reload, you'll see the miner switch to the IDLE state, but shortly afterwards, some channels on the channel list will change their status from `OFFLINE ❌` to `OFFLINE ⌛`, indicating that they're about to be checked if the stream is actually ONLINE, as an event indicating so was received. 2 minutes later, a channel will update it's status to `ONLINE ✔`, triggering a switch event, and causing the miner to start mining as usual.

Ref issues for more info on the above: https://github.com/DevilXD/TwitchDropsMiner/issues/537, https://github.com/DevilXD/TwitchDropsMiner/issues/541, https://github.com/DevilXD/TwitchDropsMiner/issues/551.

That's how the current master branch of mine works, until I can rewrite the commented out code, as it can be optimized to not send up to ~200 GQL requests at once, which is what happens if you have several games added to the Priority list, and they all together happen to reach the channels limit of the miner - which is also why this issue happens only to some people, and reproducing it is "unreliable".

**Comment by JourneyOver** [comment]
@Windows200000 lol did you have a stroke while writing that last message xD

@DevilXD hmm, I'll push that commit into my repo and keep an eye on things to see if it makes things better or not.

**Comment by Windows200000** [comment]
> @Windows200000 lol did you have a stroke while writing that last message xD
> 
> @DevilXD hmm, I'll push that commit into my repo and keep an eye on things to see if it makes things better or not.

I just have a new phone without a broken screen and am getting used to typing with fingers again. I'll correct it 😅

**Comment by JourneyOver** [comment]
Well to make an update on the situation since merging in the https://github.com/DevilXD/TwitchDropsMiner/commit/f705cc1527e806bb979df9e0dbd077d93728160c commit to my repo and testing things out, I have yet to see any `Cannot connect to Twitch, retrying in X seconds` so far, so it seems to fix this issue. I'll continue to keep an eye on things over the next day or two and if anything comes up then I'll report back.

**Comment by JourneyOver** [comment]
Another update on things, everything had been running perfectly fine since my last message (albiet a lot of it was without it actually farming anything since I had no campaigns to farm during a good portion of that time) up until about an ~2-3 hours ago when it started farming a campaign that had finally become active and then I eventually started hitting a `ERROR: Failed to watch all of 0 Broadcast qualities. Can be ignored if occuring up to ~15x/hour.` that spammed my logs for about ~6 minutes before my auto restart of the container kicked in due to the healthcheck..

Unsure of what exactly caused it but anyways here is my log (it's somewhat of a fresh log as I did restart my server last night)..
[twitchdropsminer_logs.txt](https://github.com/user-attachments/files/16901769/twitchdropsminer_logs.txt)

**Comment by JourneyOver** [comment]
@DevilXD unsure of what is going on but I've recently noticed that the change you are talking about in https://github.com/Windows200000/TwitchDropsMiner-updated/issues/172#issuecomment-2328409646 with commit https://github.com/DevilXD/TwitchDropsMiner/commit/f705cc1527e806bb979df9e0dbd077d93728160c makes it so that sometimes a channel never seems to come online in the miner even though it is clearly online on the site. I've tested this with the default version of the bot (as in from your own repo) as well and not a forked version and it has the same problem so I'm unsure if you want me to make an issue in your repo as well.

Example:
I have ravendawn in my priority list along with a bunch of other games, and there are plenty of channels online for ravendawn (some channels have been streaming for hours) with drops active for it, and there is a drop going on currently until the 16th, but running the miner it never seems to pick up any of the online channels even after several hours (I tested letting it run for like ~7 hours and it never seemed to see a ravendawn channel online).

Once I reverted the code change from that commit (so made it active again instead of commented out) though it ofc never had an issue with seeing any of the channels online and it instantly started mining... I'm unsure if the problem is affecting any other games in my prio list or not but so far (I'm sure it probably is though)
