### ISSUE TITLE
Output doesn't work properly

### ISSUE THREAD

**Issue by Kuddus73** [Windows200000/TwitchDropsMiner-updated#34]
The "Output" cell only shows details for a few seconds at the beginning of when you open the app and then it stops showing anything.

The output doesn't show all the points earned like it used to do before.
However, the mining does work fine as the drop was automatically claimed on Twitch after the required time but again, like the points, the claiming wasn't shown in the output.
![Screenshot (1009)](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/127908708/9eb55c1c-6085-466d-9631-82331c87d185)

**Comment by Windows200000** [comment]
@Kuddus73 That is a little weird, since the only thing I changed beyond the independent claim requests was making seconds available as cache to not advance minutes_watched until seconds are at 0. I'll admit that's janky, but the result is an accurate progress remaining counter and the minutes_watched counter increases as before.

My guess would then be, that this has to do with the twitch API change, that also caused the minute_watched event to be redundant. Can you check whether you still get channel points? This isn't the purpose of this project anyways and I never cared for them, but it might help someone else find out what's going on.

**Comment by Windows200000** [comment]
Gonna merge this into #23
