### ISSUE TITLE
Windows Defender now flag app as virus

### ISSUE THREAD

**Issue by dogodogowoof** [Windows200000/TwitchDropsMiner-updated#55]
Automatically deletes the executable after trying to make any kind of operations.

Happens to old and new build of the branch

![image](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/31750934/3048af5f-a51c-4837-bb6b-14907cd8171e)

**Comment by Windows200000** [comment]
This has always happened afaik. Maybe DevilXD signs the actual releases?

**Comment by dogodogowoof** [comment]
I was running an old version of this branch for a while with no issues. Just closed it to restart the app and see something, when I reopened it, it deleted it (it even deleted the start menu shortcut I had). 

Went to download the latest build of this branch and the same overall behavior happened, but it gives the prompt screenshotted.

**Comment by Windows200000** [comment]
You have to go to defender antivirus and revert it. Afaik this also happens with the original.

**Comment by letum00** [comment]
I've only ever compiled my own copies so never had the behavior here, however my friend who tried the windows binary has experienced the same virus detection issue. Here is a VirusTotal scan. If there is not a virus and these are false positives, I think it's possible to get them corrected with the vendors, but it's probably not worth your time.

https://www.virustotal.com/gui/file/f30790d10e26f9fb5214b93fd1d4abd0f39152ff04d5e6bbe9b4638d745a92f4

**Comment by dogodogowoof** [comment]
is there any world where these positives are fixed in a future release?

**Comment by automatic-gaming** [comment]
It's a problem with PyInstaller. Sometimes reverting to an older version before compiling can prevent these kinds of false positives.

**Comment by Windows200000** [comment]
> Here is a VirusTotal scan.

Well, Avast...... xD Also, looking at the behavior on virustotal, it doesn't like it being compiled python and the foreign letters in translation names and a bunch of other stuff related to how this project and probably python in general does things.

> Here is a VirusTotal scan. If there is not a virus and these are false positives, I think it's possible to get them corrected with the vendors, but it's probably not worth your time.

Afaik vendors won't care unless a LOT of people use it. It's not like they could just whitelist it, because without actual experts verifying it, there *could* be a virus in them. I mean, I theoretically could just swap the exe in releases and that's that.


> is there any world where these positives are fixed in a future release?

For the reasons mentioned above and the ability for anyone to just compile themselves, especially using an automated script like the one I shared in the original repo, probably not.

> It's a problem with PyInstaller. Sometimes reverting to an older version before compiling can prevent these kinds of false positives.

If someone finds an easy way, I can adopt it, but I don't have that much time currently, and I don't consider it something worth spending time on.

**Comment by Windows200000** [comment]
I'll leave this open, maybe someone finds something, but it looks like that's just how it's gonna be with python...

**Comment by Kimarnic** [comment]
It always did, just add the folder as an exclude in Windows Defender, it's not a virus since I've used it for a year...

**Comment by Windows200000** [comment]
> It always did, just add the folder as an exclude in Windows Defender, it's not a virus since I've used it for a year...

That's not how it works, I can add any exe I want to release, it could both be just a virus or a virus hidden within the working app.
